//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingTheme {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawingTheme.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accesoires.
        /// </summary>
        public static string Accesoires {
            get {
                return ResourceManager.GetString("Accesoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string Account_Settings {
            get {
                return ResourceManager.GetString("Account Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Accesoires.
        /// </summary>
        public static string AddAccesoires {
            get {
                return ResourceManager.GetString("AddAccesoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Component.
        /// </summary>
        public static string AddComponent {
            get {
                return ResourceManager.GetString("AddComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Category.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Component.
        /// </summary>
        public static string AddNewComponent {
            get {
                return ResourceManager.GetString("AddNewComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Role.
        /// </summary>
        public static string AddNewRole {
            get {
                return ResourceManager.GetString("AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Sub Category.
        /// </summary>
        public static string AddNewSubCategory {
            get {
                return ResourceManager.GetString("AddNewSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role, if it does not exist.
        /// </summary>
        public static string Addrole_ifitdoesnotexist {
            get {
                return ResourceManager.GetString("Addrole,ifitdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role if it does not exist.
        /// </summary>
        public static string Addroleifitdoesnotexist {
            get {
                return ResourceManager.GetString("Addroleifitdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Of Water.
        /// </summary>
        public static string AmountOfWater {
            get {
                return ResourceManager.GetString("AmountOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this  information.
        /// </summary>
        public static string Areyousurewanttodeletethisinformation {
            get {
                return ResourceManager.GetString("Areyousurewanttodeletethisinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to sign in.
        /// </summary>
        public static string Backtosignin {
            get {
                return ResourceManager.GetString("Backtosignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM.
        /// </summary>
        public static string BOM {
            get {
                return ResourceManager.GetString("BOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM Relevant.
        /// </summary>
        public static string BOMRelevant {
            get {
                return ResourceManager.GetString("BOMRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build, run, and scale your digital designs of gardens - end to end and more.
        /// </summary>
        public static string Build_run_andscaleyourdigitaldesignsofgardens_endtoendandmore {
            get {
                return ResourceManager.GetString("Build,run,andscaleyourdigitaldesignsofgardens-endtoendandmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build digital designs with.
        /// </summary>
        public static string Builddigitaldesignswith {
            get {
                return ResourceManager.GetString("Builddigitaldesignswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category List.
        /// </summary>
        public static string CategoryList {
            get {
                return ResourceManager.GetString("CategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientID.
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE.
        /// </summary>
        public static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component List.
        /// </summary>
        public static string ComponentList {
            get {
                return ResourceManager.GetString("ComponentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Option.
        /// </summary>
        public static string ControlOption {
            get {
                return ResourceManager.GetString("ControlOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer List.
        /// </summary>
        public static string CustomerList {
            get {
                return ResourceManager.GetString("CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Component.
        /// </summary>
        public static string DeleteComponent {
            get {
                return ResourceManager.GetString("DeleteComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer.
        /// </summary>
        public static string DeleteCustomer {
            get {
                return ResourceManager.GetString("DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw New Plan.
        /// </summary>
        public static string DrawNewPlan {
            get {
                return ResourceManager.GetString("DrawNewPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinking water separation station.
        /// </summary>
        public static string Drinkingwaterseparationstation {
            get {
                return ResourceManager.GetString("Drinkingwaterseparationstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinking Water Source.
        /// </summary>
        public static string drinkingwatersource {
            get {
                return ResourceManager.GetString("drinkingwatersource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Area.
        /// </summary>
        public static string DryArea {
            get {
                return ResourceManager.GetString("DryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Component.
        /// </summary>
        public static string EditComponent {
            get {
                return ResourceManager.GetString("EditComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter order name.
        /// </summary>
        public static string Enterordername {
            get {
                return ResourceManager.GetString("Enterordername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address you used when you joined and we&apos;ll send you instructions to reset your password..
        /// </summary>
        public static string Entertheemailaddressyouusedwhenyoujoinedandwe_llsendyouinstructionstoresetyourpassword_ {
            get {
                return ResourceManager.GetString("Entertheemailaddressyouusedwhenyoujoinedandwe\'llsendyouinstructionstoresetyourpas" +
                        "sword.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter included.
        /// </summary>
        public static string Filterincluded {
            get {
                return ResourceManager.GetString("Filterincluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for drinking water source.
        /// </summary>
        public static string fordrinkingwatersource {
            get {
                return ResourceManager.GetString("fordrinkingwatersource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string Forgotpassword {
            get {
                return ResourceManager.GetString("Forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPassword_ {
            get {
                return ResourceManager.GetString("ForgotPassword?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for rainwater source.
        /// </summary>
        public static string forrainwatersource {
            get {
                return ResourceManager.GetString("forrainwatersource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for well water source.
        /// </summary>
        public static string forwellwatersource {
            get {
                return ResourceManager.GetString("forwellwatersource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Wet.
        /// </summary>
        public static string GetWet {
            get {
                return ResourceManager.GetString("GetWet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedge.
        /// </summary>
        public static string Hedge {
            get {
                return ResourceManager.GetString("Hedge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image opacity.
        /// </summary>
        public static string Imageopacity {
            get {
                return ResourceManager.GetString("Imageopacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor.
        /// </summary>
        public static string Indoor {
            get {
                return ResourceManager.GetString("Indoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Location.
        /// </summary>
        public static string InstallationLocation {
            get {
                return ResourceManager.GetString("InstallationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation Computer Indoor.
        /// </summary>
        public static string IrrigationComputerindoor {
            get {
                return ResourceManager.GetString("IrrigationComputerindoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation Computer Max Station.
        /// </summary>
        public static string IrrigationComputermaxstation {
            get {
                return ResourceManager.GetString("IrrigationComputermaxstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation Computer Outdoor.
        /// </summary>
        public static string IrrigationComputeroutdoor {
            get {
                return ResourceManager.GetString("IrrigationComputeroutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation Computer Smarphone.
        /// </summary>
        public static string IrrigationComputersmarphone {
            get {
                return ResourceManager.GetString("IrrigationComputersmarphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation Wiring Max Station.
        /// </summary>
        public static string IrrigationWiringMaxStation {
            get {
                return ResourceManager.GetString("IrrigationWiringMaxStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send emails to admin?.
        /// </summary>
        public static string IsAdminReceived {
            get {
                return ResourceManager.GetString("IsAdminReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string Itemname {
            get {
                return ResourceManager.GetString("Itemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawn.
        /// </summary>
        public static string Lawn {
            get {
                return ResourceManager.GetString("Lawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Angle.
        /// </summary>
        public static string MaxAngle {
            get {
                return ResourceManager.GetString("MaxAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh105.
        /// </summary>
        public static string mh105 {
            get {
                return ResourceManager.GetString("mh105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh180.
        /// </summary>
        public static string mh180 {
            get {
                return ResourceManager.GetString("mh180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh210.
        /// </summary>
        public static string mh210 {
            get {
                return ResourceManager.GetString("mh210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh270.
        /// </summary>
        public static string mh270 {
            get {
                return ResourceManager.GetString("mh270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh360.
        /// </summary>
        public static string mh360 {
            get {
                return ResourceManager.GetString("mh360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh45.
        /// </summary>
        public static string mh45 {
            get {
                return ResourceManager.GetString("mh45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh90.
        /// </summary>
        public static string mh90 {
            get {
                return ResourceManager.GetString("mh90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh general.
        /// </summary>
        public static string mhgeneral {
            get {
                return ResourceManager.GetString("mhgeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Angle.
        /// </summary>
        public static string MinAngle {
            get {
                return ResourceManager.GetString("MinAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER#.
        /// </summary>
        public static string ORDER_ {
            get {
                return ResourceManager.GetString("ORDER#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order List.
        /// </summary>
        public static string OrderList {
            get {
                return ResourceManager.GetString("OrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER NAME.
        /// </summary>
        public static string ORDERNAME {
            get {
                return ResourceManager.GetString("ORDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER NUMBER.
        /// </summary>
        public static string ORDERNUMBER {
            get {
                return ResourceManager.GetString("ORDERNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outdoor.
        /// </summary>
        public static string outdoor {
            get {
                return ResourceManager.GetString("outdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENTID.
        /// </summary>
        public static string PAYMENTID {
            get {
                return ResourceManager.GetString("PAYMENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT STATUS.
        /// </summary>
        public static string PAYMENTSTATUS {
            get {
                return ResourceManager.GetString("PAYMENTSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal Settings.
        /// </summary>
        public static string PaypalSettings {
            get {
                return ResourceManager.GetString("PaypalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE exceed max water source m³/h now draw new one!.
        /// </summary>
        public static string PEexceedmaxwatersourcenowdrawnewone_ {
            get {
                return ResourceManager.GetString("PEexceedmaxwatersourcenowdrawnewone!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Amount.
        /// </summary>
        public static string PendingAmount {
            get {
                return ResourceManager.GetString("PendingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Transactions.
        /// </summary>
        public static string PendingTransaction {
            get {
                return ResourceManager.GetString("PendingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline Max Length.
        /// </summary>
        public static string PipelineMaxLength {
            get {
                return ResourceManager.GetString("PipelineMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        public static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan List.
        /// </summary>
        public static string Planlist {
            get {
                return ResourceManager.GetString("Planlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner Component.
        /// </summary>
        public static string Plannercomponent {
            get {
                return ResourceManager.GetString("Plannercomponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre View.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE.
        /// </summary>
        public static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per unit.
        /// </summary>
        public static string Priceperunit {
            get {
                return ResourceManager.GetString("Priceperunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile1 {
            get {
                return ResourceManager.GetString("Profile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        public static string QTY {
            get {
                return ResourceManager.GetString("QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUANTITY.
        /// </summary>
        public static string QUANTITY {
            get {
                return ResourceManager.GetString("QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain Water Source.
        /// </summary>
        public static string rainwatersource {
            get {
                return ResourceManager.GetString("rainwatersource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permissions.
        /// </summary>
        public static string RolePermissions {
            get {
                return ResourceManager.GetString("RolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Management.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as PDF.
        /// </summary>
        public static string SaveasPDF {
            get {
                return ResourceManager.GetString("SaveasPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Irrigation Plans.
        /// </summary>
        public static string SaveIregationPlans {
            get {
                return ResourceManager.GetString("SaveIregationPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Key.
        /// </summary>
        public static string SecretKey {
            get {
                return ResourceManager.GetString("SecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Settings.
        /// </summary>
        public static string Security_Settings {
            get {
                return ResourceManager.GetString("Security Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set role permissions.
        /// </summary>
        public static string Setrolepermissions {
            get {
                return ResourceManager.GetString("Setrolepermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Signout1 {
            get {
                return ResourceManager.GetString("Signout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign UP.
        /// </summary>
        public static string SignUP {
            get {
                return ResourceManager.GetString("SignUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smarphone.
        /// </summary>
        public static string Smarphone {
            get {
                return ResourceManager.GetString("Smarphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP.
        /// </summary>
        public static string SMTP {
            get {
                return ResourceManager.GetString("SMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprinkler Type.
        /// </summary>
        public static string SprinklerType {
            get {
                return ResourceManager.GetString("SprinklerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL.
        /// </summary>
        public static string SSL {
            get {
                return ResourceManager.GetString("SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Angle.
        /// </summary>
        public static string StartAngle {
            get {
                return ResourceManager.GetString("StartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category List.
        /// </summary>
        public static string SubCategoryList {
            get {
                return ResourceManager.GetString("SubCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Transactions.
        /// </summary>
        public static string SuccessfulTransaction {
            get {
                return ResourceManager.GetString("SuccessfulTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw Distance Max.
        /// </summary>
        public static string ThrowDistanceMax {
            get {
                return ResourceManager.GetString("ThrowDistanceMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw Distance Min.
        /// </summary>
        public static string ThrowDistanceMin {
            get {
                return ResourceManager.GetString("ThrowDistanceMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw Height.
        /// </summary>
        public static string ThrowHeight {
            get {
                return ResourceManager.GetString("ThrowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw Width.
        /// </summary>
        public static string ThrowWidth {
            get {
                return ResourceManager.GetString("ThrowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Components.
        /// </summary>
        public static string TotalComponents {
            get {
                return ResourceManager.GetString("TotalComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Customers.
        /// </summary>
        public static string TotalCustomers {
            get {
                return ResourceManager.GetString("TotalCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total length.
        /// </summary>
        public static string Totallength {
            get {
                return ResourceManager.GetString("Totallength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total output.
        /// </summary>
        public static string Totaloutput {
            get {
                return ResourceManager.GetString("Totaloutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PRICE.
        /// </summary>
        public static string TOTALPRICE {
            get {
                return ResourceManager.GetString("TOTALPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        public static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction List.
        /// </summary>
        public static string TransactionList {
            get {
                return ResourceManager.GetString("TransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Paid.
        /// </summary>
        public static string UnPaid {
            get {
                return ResourceManager.GetString("UnPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update BOM.
        /// </summary>
        public static string UpdateBOM {
            get {
                return ResourceManager.GetString("UpdateBOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Profile Image.
        /// </summary>
        public static string UploadProfileImage {
            get {
                return ResourceManager.GetString("UploadProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER NAME.
        /// </summary>
        public static string USERNAME1 {
            get {
                return ResourceManager.GetString("USERNAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Setting.
        /// </summary>
        public static string Usersettings {
            get {
                return ResourceManager.GetString("Usersettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valvebox Circle.
        /// </summary>
        public static string valveboxcircle {
            get {
                return ResourceManager.GetString("valveboxcircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valvebox Filter.
        /// </summary>
        public static string valveboxFilter {
            get {
                return ResourceManager.GetString("valveboxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well Water Source.
        /// </summary>
        public static string wellwatersource {
            get {
                return ResourceManager.GetString("wellwatersource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
