//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingTheme {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawingTheme.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string Account_Settings {
            get {
                return ResourceManager.GetString("Account Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION.
        /// </summary>
        internal static string ACTION {
            get {
                return ResourceManager.GetString("ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Component.
        /// </summary>
        internal static string AddComponent {
            get {
                return ResourceManager.GetString("AddComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Component.
        /// </summary>
        internal static string AddNewComponent {
            get {
                return ResourceManager.GetString("AddNewComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Role.
        /// </summary>
        internal static string AddNewRole {
            get {
                return ResourceManager.GetString("AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        internal static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role, if it does not exist.
        /// </summary>
        internal static string Addrole_ifitdoesnotexist {
            get {
                return ResourceManager.GetString("Addrole,ifitdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to sign in.
        /// </summary>
        internal static string Backtosignin {
            get {
                return ResourceManager.GetString("Backtosignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build, run, and scale your digital designs of gardens - end to end and more.
        /// </summary>
        internal static string Build_run_andscaleyourdigitaldesignsofgardens_endtoendandmore {
            get {
                return ResourceManager.GetString("Build,run,andscaleyourdigitaldesignsofgardens-endtoendandmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build digital designs with.
        /// </summary>
        internal static string Builddigitaldesignswith {
            get {
                return ResourceManager.GetString("Builddigitaldesignswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientID.
        /// </summary>
        internal static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE.
        /// </summary>
        internal static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component List.
        /// </summary>
        internal static string ComponentList {
            get {
                return ResourceManager.GetString("ComponentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer List.
        /// </summary>
        internal static string CustomerList {
            get {
                return ResourceManager.GetString("CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Component.
        /// </summary>
        internal static string EditComponent {
            get {
                return ResourceManager.GetString("EditComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        internal static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        internal static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address you used when you joined and we&apos;ll send you instructions to reset your password..
        /// </summary>
        internal static string Entertheemailaddressyouusedwhenyoujoinedandwe_llsendyouinstructionstoresetyourpassword_ {
            get {
                return ResourceManager.GetString("Entertheemailaddressyouusedwhenyoujoinedandwe\'llsendyouinstructionstoresetyourpas" +
                        "sword.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        internal static string Forgotpassword {
            get {
                return ResourceManager.GetString("Forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword_ {
            get {
                return ResourceManager.GetString("ForgotPassword?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER#.
        /// </summary>
        internal static string ORDER_ {
            get {
                return ResourceManager.GetString("ORDER#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order List.
        /// </summary>
        internal static string OrderList {
            get {
                return ResourceManager.GetString("OrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER NAME.
        /// </summary>
        internal static string ORDERNAME {
            get {
                return ResourceManager.GetString("ORDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER NUMBER.
        /// </summary>
        internal static string ORDERNUMBER {
            get {
                return ResourceManager.GetString("ORDERNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENTID.
        /// </summary>
        internal static string PAYMENTID {
            get {
                return ResourceManager.GetString("PAYMENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT STATUS.
        /// </summary>
        internal static string PAYMENTSTATUS {
            get {
                return ResourceManager.GetString("PAYMENTSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal Settings.
        /// </summary>
        internal static string PaypalSettings {
            get {
                return ResourceManager.GetString("PaypalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Amount.
        /// </summary>
        internal static string PendingAmount {
            get {
                return ResourceManager.GetString("PendingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Transaction.
        /// </summary>
        internal static string PendingTransaction {
            get {
                return ResourceManager.GetString("PendingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE.
        /// </summary>
        internal static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile1 {
            get {
                return ResourceManager.GetString("Profile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permissions.
        /// </summary>
        internal static string RolePermissions {
            get {
                return ResourceManager.GetString("RolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Management.
        /// </summary>
        internal static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Key.
        /// </summary>
        internal static string SecretKey {
            get {
                return ResourceManager.GetString("SecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Settings.
        /// </summary>
        internal static string Security_Settings {
            get {
                return ResourceManager.GetString("Security Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set role permissions.
        /// </summary>
        internal static string Setrolepermissions {
            get {
                return ResourceManager.GetString("Setrolepermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign UP.
        /// </summary>
        internal static string SignUP {
            get {
                return ResourceManager.GetString("SignUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP.
        /// </summary>
        internal static string SMTP {
            get {
                return ResourceManager.GetString("SMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL.
        /// </summary>
        internal static string SSL {
            get {
                return ResourceManager.GetString("SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Transaction.
        /// </summary>
        internal static string SuccessfulTransaction {
            get {
                return ResourceManager.GetString("SuccessfulTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Components.
        /// </summary>
        internal static string TotalComponents {
            get {
                return ResourceManager.GetString("TotalComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Customers.
        /// </summary>
        internal static string TotalCustomers {
            get {
                return ResourceManager.GetString("TotalCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PRICE.
        /// </summary>
        internal static string TOTALPRICE {
            get {
                return ResourceManager.GetString("TOTALPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        internal static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction List.
        /// </summary>
        internal static string TransactionList {
            get {
                return ResourceManager.GetString("TransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        internal static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER NAME.
        /// </summary>
        internal static string USERNAME1 {
            get {
                return ResourceManager.GetString("USERNAME1", resourceCulture);
            }
        }
    }
}
