//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingTheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        public int OrderDetailId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public string ComponentName { get; set; }
        public string ComponentCode { get; set; }
        public Nullable<double> ComponentPrice { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblComponent tblComponent { get; set; }
    }
}
