//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingTheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        public int OrderDetailId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public string SubcategoryName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> MinAngle { get; set; }
        public Nullable<double> MaxAngle { get; set; }
        public Nullable<double> ThrowDistanceMax { get; set; }
        public Nullable<double> ThrowDistanceMin { get; set; }
        public string UniqueId { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
