//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingTheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSubCategory()
        {
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
        }
    
        public int SubcategoryID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string SubcategoryName { get; set; }
        public string ComponentPiktogramm { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Price { get; set; }
        public string SprinklerType { get; set; }
        public Nullable<double> MinAngle { get; set; }
        public Nullable<double> MaxAngle { get; set; }
        public Nullable<double> ThrowDistanceMax { get; set; }
        public Nullable<double> ThrowDistanceMin { get; set; }
        public Nullable<double> ThrowWidth { get; set; }
        public Nullable<double> ThrowHeight { get; set; }
        public Nullable<double> mhgeneral { get; set; }
        public Nullable<double> PipelineMaxLength { get; set; }
        public Nullable<double> IrrigationWiringMaxStation { get; set; }
        public Nullable<int> IrrigationComputermaxstation { get; set; }
        public Nullable<bool> IrrigationComputerindoor { get; set; }
        public Nullable<bool> IrrigationComputeroutdoor { get; set; }
        public Nullable<bool> IrrigationComputersmarphone { get; set; }
        public Nullable<int> valveboxcircle { get; set; }
        public Nullable<bool> valveboxFilter { get; set; }
        public Nullable<bool> drinkingwatersource { get; set; }
        public Nullable<bool> wellwatersource { get; set; }
        public Nullable<bool> rainwatersource { get; set; }
        public Nullable<double> mh45 { get; set; }
        public Nullable<double> mh90 { get; set; }
        public Nullable<double> mh105 { get; set; }
        public Nullable<double> mh180 { get; set; }
        public Nullable<double> mh210 { get; set; }
        public Nullable<double> mh270 { get; set; }
        public Nullable<double> mh360 { get; set; }
        public Nullable<bool> Plannercomponent { get; set; }
        public Nullable<bool> BOMRelevant { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
    }
}
