//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingTheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetting
    {
        public int SettingId { get; set; }
        public string SecretKey { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ClientID { get; set; }
        public Nullable<int> Port { get; set; }
        public string SMTP { get; set; }
        public string Mode { get; set; }
        public Nullable<int> Editby { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
